"""empty message

Revision ID: 8fc91b30bf33
Revises: ed72b8a582e0
Create Date: 2022-08-16 11:39:12.643675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc91b30bf33'
down_revision = 'ed72b8a582e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('requests_contract_id_key', 'requests', type_='unique')
    op.drop_constraint('requests_request_id_key', 'requests', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('requests_request_id_key', 'requests', ['request_id'])
    op.create_unique_constraint('requests_contract_id_key', 'requests', ['contract_id'])
    # ### end Alembic commands ###
