"""empty message

Revision ID: ed72b8a582e0
Revises: fee5426727f3
Create Date: 2022-08-16 10:45:09.407831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed72b8a582e0'
down_revision = 'fee5426727f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('operators_op_surname_key', 'operators', type_='unique')
    op.drop_column('operators', 'op_surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('op_surname', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.create_unique_constraint('operators_op_surname_key', 'operators', ['op_surname'])
    # ### end Alembic commands ###
